### PR TITLE
fix Label render and add test case

### LINKED ISSUE #2623: Share Distance Field of Label work wrong
- axmol version: 2.6.0
- devices test on: All device
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

1. use FontFreeType::setShareDistanceFieldEnabled(true);
2.use Button with Title:
```
    auto button = ax::ui::Button::create("bgBt.png");
    button->setTitleText("Title");
    button->setTitleColor(Color3B::RED);
    button->setTitleFontName("fonts/Marker Felt.ttf");
    button->setTitleFontSize(40);
    this->addChild(button);
    button->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
```
Size not change (any value)

now:
Image

correct:

Image

im add `_contentDirty = true;` to `Label::setTTFConfig` and it work ok, 
But I'm not sure if it has any other effect

### LINKED ISSUE #2626: Label render with Effect wrong
- axmol version: 2.7.1
- devices test on: All devices
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 

1. Bold and Shadow not work same time: Bold = Shadow + Kerning
Image

and
2. Glow and Outline not work same time: _currLabelEffect just save (Outline or Glow or Normal), If you enable both at the same time, then disable one of them, you will lose both.
Image

### PR DESCRIPTION
**Pull request by NgVThangBz**
fix Label render
Add test Label render:
Normal, SDF
Glow, Outline, Shadow, Bold
Change Size font, Scale, size outline

Screenshot 2025-08-07 at 10 11 58

### CODE REVIEW

**Comment by aismann** [comment]
Nice tester!
Can you look again: Size it not resizing SDF font (A new bug or a tester issue, I have not look at the source for now) 
image

**Comment by NgVThangBz** [comment]
@aismann im just add test, I think we should add test first, then fix bug
test in: https://github.com/NgVThangBz/axmol/tree/Fix-Label-Render
fix in: https://github.com/NgVThangBz/axmol/tree/fix-Label-SDF-render

**Comment by aismann** [comment]
> @aismann im just add test, I think we should add test first, then fix bug test in: https://github.com/NgVThangBz/axmol/tree/Fix-Label-Render fix in: https://github.com/NgVThangBz/axmol/tree/fix-Label-SDF-render

Ok I see.
Plz add the fix also to this PR (title have to be changed?)
Fix and a needed test on the same PR  is faster and the expected result (the tester shows the known bug) The goal is the fix in this PR.
Thanks.

**Comment by halx99** [comment]
> > @aismann im just add test, I think we should add test first, then fix bug test in: https://github.com/NgVThangBz/axmol/tree/Fix-Label-Render fix in: https://github.com/NgVThangBz/axmol/tree/fix-Label-SDF-render
> 
> Ok I see. Plz add the fix also to this PR (title have to be changed?) Fix and a needed test on the same PR is faster and the expected result (the tester shows the known bug) The goal is the fix in this PR. Thanks.

agree

**Comment by aismann** [comment]
@NgVThangBz 
You have changed (fix) a little bit more as expected by me.
Can you give some more information (screenshot?) what all is fixed with this PR?
Thanks.

**Comment by NgVThangBz** [comment]
Here are some initial bugs I found, then fixed each bug

Size SDF not change when change size font
Font SDF changeSize

size text not correct when unBlod

https://github.com/user-attachments/assets/7e49f75e-d27b-4af3-b6d4-9af4873d11ec

Outline enable->change size ->size no change and effect lost
Screenshot 2025-08-07 at 13 23 56

Glow enable->change size ->size no change and effect lost(both)
Screenshot 2025-08-07 at 13 24 13

**Comment by halx99** [comment]
does all bugs releated to SDF ?

**Comment by NgVThangBz** [comment]
@halx99 some SDF and and some both

**Comment by aismann** [comment]
@NgVThangBz 
Can you improve the tester?
Current situation:
image

I think the outline slider should only be enabled/shown if the Outline checkbox "checked"
If  checked:
image

If NOT checked:
image

**Comment by NgVThangBz** [comment]
@aismann im update it

**Comment by aismann** [comment]
@halx99 
Should the Codacy static analysis not be the fist check ?
image

**Comment by halx99** [comment]
> @halx99 Should the Codacy static analysis not be the fist check ? image

I can't control the check order

**Comment by aismann** [comment]
@NgVThangBz 
I have once again some improvements for the test:
I belive Outline and Glow cant be used on the same font  toghether (can you improve the checkbox behavior again?)
Or is it a next issue and should fix?

**Comment by aismann** [comment]
I have once again some improvements for the test:
I belive Outline and Glow cant be used on the same font toghether (can you improve the checkbox behavior again?)

**Comment by NgVThangBz** [comment]
if Outline enable -> glow will disable (if enable) ,
same with  Glow?

**Comment by NgVThangBz** [comment]
if Outline enable -> glow will disable (if enable) ,
same with  Glow?

**Comment by aismann** [comment]
> if Outline enable -> glow will disable (if enable) , same with Glow?

I thick 2 radiobuttons be better as 2 checkboxes

**Comment by aismann** [comment]
If you wish, the “title” of the test can also be more self-explanatory:
“TTF font: SDF vs. Normal”
And on the second line the issue number only (e.g.: "Issue xxx")

**Comment by NgVThangBz** [comment]
>@aismann radiobuttons? outline, glow and normal?

Sounds good. 

/Edit:
'normal' will 'uncheck' all font settings (checkboxes) too, right?

File: core/2d/Label.cpp [hunk 1]
```diff
@@ -1293,22 +1293,23 @@ bool Label::updateTTFConfigInternal()
...
     else
     {
-        _currLabelEffect = LabelEffect::NORMAL;
-        updateShaderProgram();
+        if(_currLabelEffect != LabelEffect::GLOW){
+            _currLabelEffect = LabelEffect::NORMAL;
+        }
     }
-
+    updateShaderProgram();
```
Comment (halx99) [inline core/2d/Label.cpp]: does `updateShaderProgram` needed always, if not, better logic should be:
```cpp
if (_fontConfig.outlineSize > 0)
{
    _useA8Shader     = false;
    _currLabelEffect = LabelEffect::OUTLINE;
    updateShaderProgram();
}
else if (_currLabelEffect != LabelEffect::GLOW)
{
    _currLabelEffect = LabelEffect::NORMAL;
    updateShaderProgram();
}
```

**Comment by aismann** [comment]
@halx99 
By the way:
I think its time to rename Menu entry "Node: Label - New API" to e.g. "Node: Label - SDF/Normal" or "Node: Label" only.
=> "New API" has not realy an useful info.

**Comment by NgVThangBz** [comment]
new UI

https://github.com/user-attachments/assets/fe1e0b76-066a-4b7f-819b-42866a516318

File: core/2d/Label.cpp [hunk 2]
```diff
@@ -1370,14 +1371,14 @@ void Label::enableGlow(const Color4B& glowColor)
...
+        config.outlineSize          = 0;
         if (_fontConfig.distanceFieldEnabled == false)
         {
-            auto config                 = _fontConfig;
-            config.outlineSize          = 0;
             config.distanceFieldEnabled = true;
-            setTTFConfig(config);
-            _contentDirty = true;
         }
+        setTTFConfig(config);
```
Comment (halx99) [inline core/2d/Label.cpp]: better logic:

```cpp
int mods                    = 0;
auto config                 = _fontConfig;
if (config.outlineSize != 0)
{
    config.outlineSize = 0;
    ++mods;
}

if (!_fontConfig.distanceFieldEnabled)
{
    config.distanceFieldEnabled = true;
    ++mods;
}
if (mods)
{
    setTTFConfig(config);
    _contentDirty = true;
}
```

**Comment by halx99** [comment]
> @halx99 By the way: I think its time to rename Menu entry "Node: Label - New API" to e.g. "Node: Label - SDF/Normal" or "Node: Label" only. => "New API" has not realy an useful info.

Yes, there is no old API in axmol, so  just `Node: Label`, but not related to this PR

**Comment by aismann** [comment]
@NgVThangBz @halx99 
what you think about this UI design:
image

or this:
image

File: core/2d/Label.cpp (hunk 2 above)
Comment (NgVThangBz) [reply core/2d/Label.cpp]: why need  enable distanceFieldEnabled with glow?
```
        if (!_fontConfig.distanceFieldEnabled)
        {
            config.distanceFieldEnabled = true;
            ++mods;
        }
```

**Comment by halx99** [comment]
> new UI
> 
>  Screen.Recording.2025-08-08.at.14.10.21.mov

I think it's ok, it just test case, so no need take much time to optimize ui layout

File: core/2d/Label.cpp (hunk 2 above)
Comment (halx99) [reply core/2d/Label.cpp]: > why need enable distanceFieldEnabled with glow?
> 
> ```
>         if (!_fontConfig.distanceFieldEnabled)
>         {
>             config.distanceFieldEnabled = true;
>             ++mods;
>         }
> ```

not sure why, but the logic is comes from cocos2d-x-4.0

Comment (NgVThangBz) [reply core/2d/Label.cpp]: @halx99  please help me check all code in Label::enableGlow

Comment (halx99) [reply core/2d/Label.cpp]: there is only distance field glow shader, I guess
image

**Comment by aismann** [comment]
> > new UI
> > Screen.Recording.2025-08-08.at.14.10.21.mov
> 
> I think it's ok, it just test case, so no need take much time to optimize ui layout

Correct. But we do it one time forever.
Feeling is better if the (test) UI is straight forward and clear too
@NgVThangBz 
You can make it as you want.

File: tests/cpp-tests/Source/LabelTest/LabelTestNew.cpp [hunk 3]
```diff
@@ -1329,6 +1331,208 @@ std::string LabelTTFDistanceField::subtitle() const
...
+    initToggleLabel("enableItalics",Vec2(size.width*0.15, size.height*0.25),[=, this](Object*obj, ax::ui::CheckBox::EventType type){
+        if(type == ax::ui::CheckBox::EventType::SELECTED){
+            _labelSDF->enableItalics();
+            _labelNormal->enableItalics();
+        }else{
+            _labelSDF->disableEffect(ax::LabelEffect::ITALICS);
+            _labelNormal->disableEffect(ax::LabelEffect::ITALICS);
+        }
+    });
+    initToggleLabel("enableOutline",Vec2(size.width*0.15, size.height*0.35),[=, this](Object*obj, ax::ui::CheckBox::EventType type){
```
Comment (halx99) [inline tests/cpp-tests/Source/LabelTest/LabelTestNew.cpp]: Please use code editor to correct indent

File: core/2d/Label.cpp (hunk 2 above)
Comment (NgVThangBz) [reply core/2d/Label.cpp]: so, it will:
```
        auto config                 = _fontConfig;
        int mods                    = 0;
        if (config.outlineSize > 0)
        {
            config.outlineSize = 0;
            ++mods;
        }
        if (!_fontConfig.distanceFieldEnabled)
        {
            config.distanceFieldEnabled = true;
            ++mods;
        }
        if (mods)
        {
            setTTFConfig(config);
            _contentDirty = true;
        }
```

Comment (halx99) [reply core/2d/Label.cpp]: you can add some comment at here, i.e. `axmol only support Glow in distance field rendering mode`

Comment (halx99) [reply core/2d/Label.cpp]: > so, it will:
> 
> ```
>         auto config                 = _fontConfig;
>         int mods                    = 0;
>         if (config.outlineSize > 0)
>         {
>             config.outlineSize = 0;
>             ++mods;
>         }
>         if (!_fontConfig.distanceFieldEnabled)
>         {
>             config.distanceFieldEnabled = true;
>             ++mods;
>         }
>         if (mods)
>         {
>             setTTFConfig(config);
>             _contentDirty = true;
>         }
> ```

lgtm

Comment (NgVThangBz) [reply core/2d/Label.cpp]: > you can add some comment at here, i.e. `axmol only support Glow in distance field rendering mode`

but there is a difference:
Screenshot 2025-08-08 at 15 23 35

Comment (halx99) [reply core/2d/Label.cpp]: mayba another bug, let's check it

Comment (halx99) [reply core/2d/Label.cpp]: I got it, will check how to fix it, but not related to this PR

**Comment by NgVThangBz** [comment]
I have pushed the code

**Comment by aismann** [comment]
Resizing the font is working now
=> Some other bugs be there which not part of this PR

@NgVThangBz 
Very good work, thanks.

@halx99 
from my side, PR can be merge

**Review by halx99 — APPROVED** [review]

**Comment by halx99** [comment]
Merged, thanks @NgVThangBz
