### PR TITLE
[FairyGUI] Add support for blending

### LINKED ISSUE #2486: FairyGUI: Unable to Use BlendMode due to The Lack of Its Implementation
- Axmol version:2.4.0
- Devices test on: Windows 11 24H2 (26100.3476)
- Developing environments
   - (Only in) Visual Studio: 
      - VS version: 2022 (17.13.5)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0
   - CMake version: 3.31.3

## Description of the problem:

Blend Mode isn't working, since **"It's not implemented"**. Inside the source file "GObject.cpp" we can find that the BlendMode is able to load, YET ignored ultimately(on line 872).

Image

## Steps to Reproduce:

It's easy to reproduce this bug, by creating an Object with BlendMode in a component, and loading it in Axmol Engine.

1. Open FairyGUI, and create an Object with any kinds of BlendMode;
2. Save our project, publish it, and normally load it afterwards in Axmol Engine;
3. Since BlendMode is ignored on loading the package, **every object using BlendMode looks the same as the one without using BlendMode**.

Here's how it presented in my computer.

1. Create a GGraph "test" with BlendMode "Add", color "#00CC00" inside a GComponent named "Dashboard", a member of the package "SearchScene";

Image

2. Save and publish the package normally.
3. Load the package in Axmol Engine, and create "Dashboard":

```cpp
void SearchScene::init(){
    ...
    UIPackage::addPackage("SearchScene");
    _dashboard=UIPackage::createObject("SearchScene", "Dashboard")
        ->as<GComponent>();
    _GROOT->addChild(_dashboard);
    ...
}
```

4. Compile and run the project, and the GGraph isn't using BlendMode.

Image

## Another Issue:

Stroke for GTextField isn't working, returning **"Stroke Currently only supported on iOS and Android!"** in console. This is occurred on loading/changing RichText.

Image
Image

### PR DESCRIPTION
**Pull request by rh101**
## Describe your changes

 `DrawNode` now inherits from `BlendProtocol`, since it does support blending.  Also, ensure that the set `BlendFunc` is actually used, because it was hard-coded previously, so never used the correct blending modes. The change should not affect existing usage at all, since the default `BlendFunc` was `BlendFunc::ALPHA_PREMULTIPLIED`, which is `{backend::BlendFactor::ONE, backend::BlendFactor::ONE_MINUS_SRC_ALPHA}`, the same as what was being hard-coded:

```
blendDescriptor.sourceRGBBlendFactor        = backend::BlendFactor::ONE;
blendDescriptor.destinationRGBBlendFactor   = backend::BlendFactor::ONE_MINUS_SRC_ALPHA;
blendDescriptor.sourceAlphaBlendFactor      = backend::BlendFactor::ONE;
blendDescriptor.destinationAlphaBlendFactor = backend::BlendFactor::ONE_MINUS_SRC_ALPHA;
```
Which is now:
```
blendDescriptor.sourceRGBBlendFactor        = _blendFunc.src;
blendDescriptor.destinationRGBBlendFactor   = _blendFunc.dst;
blendDescriptor.sourceAlphaBlendFactor      = _blendFunc.src;
blendDescriptor.destinationAlphaBlendFactor = _blendFunc.dst;
```

Nothing else changes, as this is primarily an enhancement to allow blending when using FairyGUI components.  The FairyGUI code changes are based of FairyGUI libraries for other engines, so the API is similar to their other implementations.

## Issue ticket number and link
#2486 

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

File: extensions/fairygui/src/fairygui/display/BlendMode.cpp [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    }
+
+    auto&& children = node->getChildren();
+    for (auto&& child : children)
+    {
+        apply(child, blendFunc);
+    }
+}
+
+void BlendModeUtils::override(BlendMode blendMode,
```
Comment (halx99) [inline extensions/fairygui/src/fairygui/display/BlendMode.cpp]: should avoid use c++ keyword as symbol, maybe rename to `update`

**Review by halx99 — CHANGES_REQUESTED** [review]

File: extensions/fairygui/src/fairygui/display/BlendMode.cpp (hunk 1 above)
Comment (rh101) [reply extensions/fairygui/src/fairygui/display/BlendMode.cpp]: Yes, I noticed that, since I was just following their current implementation from [here](https://github.com/fairygui/FairyGUI-cocoscreator/blob/ccc3.0/source/src/display/BlendMode.ts).

I'll change it now to avoid the confusion.

Comment (rh101) [reply extensions/fairygui/src/fairygui/display/BlendMode.cpp]: Actually, how about `overrideBlendMode`, since it states the purpose of the method?

Comment (halx99) [reply extensions/fairygui/src/fairygui/display/BlendMode.cpp]: > Actually, how about `overrideBlendMode`, since it states the purpose of the method?

it's ok
