### PR TITLE
[Apple] Fix media controls not appearing

### LINKED ISSUE #1811: VideoPlayer controls buttons not showing
Hi guys,
With cocos2d-x when you start the video VideoPlayer, and tap on the video playing, the video will stop and you will have the video controls showing. This is the normal behavior for any app (not only for coco2d-x apps):

With Axmol, when you tap on the video playing, the behavior is completely different (it doesn’t make it user friendly):
1) When you tap on the video playing, the video doesn’t stop playing. It should stop playing.

2) The video controls will not appear. They should appear.

Please see attached screenshots to see how it should look. And what is happening with Axmol.

This is a normal case (the video controls are accessible). and when you tap on it, it will stop playing:

normalBehavior

This is Axmol bug, where the video controls are not accessible an when you tap on it it will not stop playing:

Screenshot 2024-04-10 at 6 20 39 PM

You can try with the url provided in the VideoPlayer test:  https://storage.googleapis.com/exoplayer-test-media-1/mp4/android-screens-25s.mp4

Thank you,
Stay safe

- axmol version: 2.1.2
- devices test on: iPhon 11, 12, 13, 14
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - Visual Studio: 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version:  3.29.0
Steps to Reproduce:

1. Build a small test App with the video VideoPlayer (or use the test App provided by Axmol)
2. use the url provided by Axmol to display the video (https://storage.googleapis.com/exoplayer-test-media-1/mp4/android-screens-25s.mp4)
3. When the video is playing, tap on it

Thank you,
Stay safe

### PR DESCRIPTION
**Pull request by rh101**
## Describe your changes
This allows the media controls texture to be created correctly on both OpenGL and Metal renderer backends.

Added support for changing the height of the media timeline bar.

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

File: core/ui/UIMediaPlayer.cpp [hunk 1]
```diff
@@ -284,10 +275,17 @@ void createMediaControlTexture()
     for (auto&& item : items)
     {
         auto midPoint =
-            Vec2(border + (i * panelW) + (i * gap) + (panelW / 2.f), imageSize.height - border - (panelH / 2.f));
+        Vec2(border + (i * panelW) + (i * gap) + (panelW / 2.f), imageSize.height - border - (panelH / 2.f));
         item.second(midPoint);
+
+#if defined(AX_USE_GL) || defined(AX_USE_GLES)
```
Comment (halx99) [inline core/ui/UIMediaPlayer.cpp]:
```suggestion
#if defined(AX_USE_GL)
```

**Review by halx99 — APPROVED** [review]
